name: Test Windows Compatibility

on: [push, workflow_dispatch]

jobs:
  test-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run test script
        run: python app.py
        
      - name: Save logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-logs
          path: logs/

      - name: Create logs directory
        run: mkdir -p logs
        shell: bash